#!/bin/bash -ex

# TODO: convert to portable testinstall.py, need to run on Windows as well

python setup.py test

damnode uninstall --yes
damnode list
damnode install

[[ "`nrun node --version`" = "`node --version`" ]]
[[ "`nrun npm --version`" = "`npm --version`" ]]

# TODO: also install old version 4.x

echo "Testing completed successfully!"
